// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CustomContainer(Custom bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"custom-container\" class=\"custom-container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if Custom {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"custom-options\" class=\"custom-options\"><label for=\"custom-slug\">Custom URL Slug</label> <input type=\"text\" id=\"custom-slug\" name=\"custom_slug\" placeholder=\"e.g., my-url\"> <label for=\"url-expiration\">Expiration Time Hours ['0' for no expiration]</label> <input type=\"number\" id=\"url-expiration\" name=\"expiration\" min=\"0\" placeholder=\"24\" class=\"small\"><div class=\"checkBox-content\"><span>Link</span> <span>QR Code</span> <label class=\"checkBox\"><input type=\"checkbox\" id=\"check-link\" name=\"check-link\"><div class=\"transition\"></div></label> <label class=\"checkBox\"><input type=\"checkbox\" id=\"check-qr\" name=\"check-qr\"><div class=\"transition\"></div></label></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Empty container when \"Short\" or \"QR Code\" is selected --> <div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
